name: 部署VuePress站点

on:
  push:
    branches: [ main ] # 当代码推送到 main 分支时触发
  workflow_dispatch: # 允许在网页上手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 在一个干净的Ubuntu系统环境中运行
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装pnpm
        uses: pnpm/action-setup@v4

      - name: 安装Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 安装依赖
        run: pnpm install

      - name: 构建VuePress站点
        run: pnpm docs:build

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist # 这里放的是构建好的网站文件
          publish_branch: gh-pages # 部署到 gh-pages 分支